version: '3.1'

services:

  app:
    build:
      context: ./
      dockerfile: docker/config/php-fpm.Dockerfile
    container_name: laravel-app
    restart: always
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - internal

  db:
    image: postgres:12.7
    container_name: laravel-db
    restart: always
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: ${DB_DATABASE}
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
    working_dir: /var/www/html
    depends_on:
      - app
    networks:
      - internal

  nginx:
    build:
      context: ./
      dockerfile: docker/config/nginx.Dockerfile
    container_name: laravel-nginx
    restart: always
    volumes:
      - ./:/var/www/html
      - ./storage/app/public/:/var/www/public/storage/
    ports:
      - 8000:80
    working_dir: /var/www/html
    depends_on:
      - app
    networks:
      - internal

networks:
   internal:
     driver: bridge

